name: Repository Request
description: Request creation or update of a repository
title: "[REPO] "
labels: ["repo-request"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this repository request!

  - type: input
    id: repo-name
    attributes:
      label: Repository Name
      description: Name for the repository
      placeholder: repository_name: my-repo-name
    validations:
      required: true

  - type: dropdown 
    id: template-repo
    attributes:
      label: Template Repository
      description: Optional template repository to use
      options: 
        - "template_repository: none"
        - "template_repository: template-repo"
    validations:
      required: false

  - type: dropdown
    id: visibility
    attributes:
      label: Repository Visibility
      description: Select the visibility level for the repository
      options:
        - "repository_visibility: internal"
        - "repository_visibility: private"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Repository Description
      description: Brief description of the repository's purpose
      placeholder: |
        repository_description: >-
          Describe the purpose of this repository...
    validations:
      required: true

  - type: textarea
    id: repo-config
    attributes:
      label: Repository Configuration
      description: Repository settings (modify only if needed, leave empty for defaults)
      value: |
        repository:
          # Uncomment and modify only the settings you want to change
          # has_issues: true
          # has_projects: true
          # has_wiki: true
          # default_branch: main
          # allow_squash_merge: true
          # allow_merge_commit: true
          # allow_rebase_merge: true
          # allow_auto_merge: false
          # delete_branch_on_merge: true
          # allow_update_branch: true

  - type: textarea
    id: security-settings
    attributes:
      label: Security Settings
      description: Security-related configurations (modify only if needed, leave empty for defaults)
      value: |
        repository_security_settings:
          # Uncomment and modify only the settings you want to change
          # enableVulnerabilityAlerts: true
          # enableAutomatedSecurityFixes: true

  - type: textarea
    id: branch-protection
    attributes:
      label: Branch Protection Rules
      description: Branch protection configurations (modify only if needed, leave empty for defaults)
      value: |
        rulesets:
          # Uncomment and modify only if you need different branch protection rules
          # - name: default
          #   target: branch
          #   enforcement: active
          #   conditions:
          #     ref_name:
          #       include: ["~DEFAULT_BRANCH"]
          #   rules:
          #     - type: pull_request
          #       parameters:
          #         dismiss_stale_reviews_on_push: true
          #         require_code_owner_review: true
          #         required_approving_review_count: 2
          #         required_review_thread_resolution: true

  - type: textarea
    id: custom-properties
    attributes:
      label: Additional Settings
      description: Custom properties for the repository (required fields)
      value: |
        custom_properties:
          - name: team
            value: ""  # Required: Add your team name
          - name: cost-center
            value: ""  # Required: Add your cost center
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our repository policies
      options:
        - label: I have reviewed the repository settings and confirm they meet our organization's requirements