name: Trigger Azure DevOps Pipeline
on:
  workflow_dispatch:
jobs:
  trigger-ado-pipeline:
    runs-on: windows-latest
    environment:
        name: PUBLISH_TO_ADO
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Authenticate to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUB_ID }}
          enable-AzPSSession: true
      
      - name: Azure DevOps Pipeline Trigger
        shell: pwsh
        env:
          AZURE_DEVOPS_ORG: ${{ vars.AZURE_DEVOPS_ORG }}
          AZURE_DEVOPS_PROJECT: ${{ vars.AZURE_DEVOPS_PROJECT }}
          AZURE_DEVOPS_PIPELINE_ID: 7
        run: |
          # Get token using az cli (Azure DevOps resource ID)
          $token = (az account get-access-token --resource "499b84ac-1321-427f-aa17-267ca6975798" --query "accessToken" -o tsv)
          
          if (-not $token) {
            Write-Host "Failed to retrieve token. Trying alternate method..."
            # Alternative: get management token and use it (might work for some ADO scenarios)
            $token = (az account get-access-token --query "accessToken" -o tsv)
          }
          
          Write-Host "Access Token retrieved successfully" 
          
          $Params = @{
            OrganizationUrl = $env:AZURE_DEVOPS_ORG
            ProjectName = $env:AZURE_DEVOPS_PROJECT
            PipelineId = $env:AZURE_DEVOPS_PIPELINE_ID
            AccessToken = $token
          }
          
          ./.github/scripts/Monitor-AdoPipeline.ps1 @Params