name: Trigger Azure DevOps Pipeline

on:
  workflow_dispatch:

jobs:
  trigger-ado-pipeline:
    runs-on: windows-latest
    environment:
        name: PUBLISH_TO_ADO
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Authenticate to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUB_ID }}
          enable-AzPSSession: true
      
      - name: Azure DevOps Pipeline Trigger
        shell: pwsh
        env:
          AZURE_DEVOPS_ORG: ${{ vars.AZURE_DEVOPS_ORG }}
          AZURE_DEVOPS_PROJECT: ${{ vars.AZURE_DEVOPS_PROJECT }}
          AZURE_DEVOPS_PIPELINE_ID: 7
        run: |
          $token = (Get-AzAccessToken).token
          Write-Host "Access Token: $token"

          if (-not $token){
            Write-Host " No Access Token Found??"
          }
          
          $Params = @{
            OrganizationUrl = $env:AZURE_DEVOPS_ORG
            ProjectName = $env:AZURE_DEVOPS_PROJECT
            PipelineId = $env:AZURE_PIPELINE_ID
            $accessToken = $token
          }
          
          ./.github/scripts/Monitor-AdoPipeline.ps1 @params
