name: Monitor Azure DevOps Pipeline Details

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  trigger-ado-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Install Azure DevOps CLI extension
        run: az extension add --name azure-devops
          
      - name: Set Azure DevOps organization and project
        run: |
          az devops configure --defaults organization=https://dev.azure.com/{organization} project={project}
          
      - name: Trigger Pipeline
        id: trigger
        run: |
          RUN_DETAILS=$(az pipelines run --id {pipelineId} --branch main -o json)
          RUN_ID=$(echo $RUN_DETAILS | jq -r '.id')
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
          echo "Pipeline triggered: Build $RUN_ID"

      - name: Monitor Pipeline Progress
        run: |
          RUN_ID=${{ steps.trigger.outputs.run_id }}
          TIMEOUT_MINUTES=30
          POLL_INTERVAL_SECONDS=30
          MAX_POLLS=$((TIMEOUT_MINUTES * 60 / POLL_INTERVAL_SECONDS))
          
          monitor_pipeline() {
            # Get pipeline timeline using REST API
            local TIMELINE=$(curl -s -X GET \
              "https://dev.azure.com/{organization}/{project}/_apis/build/builds/$RUN_ID/timeline?api-version=7.0" \
              -H "Authorization: Bearer ${{ secrets.AZURE_TOKEN }}" \
              -H "Content-Type: application/json")
            
            # Get overall pipeline details
            local PIPELINE_DETAILS=$(curl -s -X GET \
              "https://dev.azure.com/{organization}/{project}/_apis/build/builds/$RUN_ID?api-version=7.0" \
              -H "Authorization: Bearer ${{ secrets.AZURE_TOKEN }}" \
              -H "Content-Type: application/json")
            
            local STATUS=$(echo "$PIPELINE_DETAILS" | jq -r '.status')
            local RESULT=$(echo "$PIPELINE_DETAILS" | jq -r '.result // "inProgress"')
            
            echo "Pipeline Status: $STATUS ($RESULT)"
            
            # Process each stage
            echo "$TIMELINE" | jq -c '.records[] | select(.type == "Stage")' | while read -r stage; do
              local STAGE_NAME=$(echo $stage | jq -r '.name')
              local STAGE_STATE=$(echo $stage | jq -r '.state')
              local STAGE_RESULT=$(echo $stage | jq -r '.result // "pending"')
              local STAGE_ID=$(echo $stage | jq -r '.id')
              
              echo "Stage: $STAGE_NAME - State: $STAGE_STATE ($STAGE_RESULT)"
              
              # Get all jobs for this stage
              echo "$TIMELINE" | jq -c --arg stageId "$STAGE_ID" \
                '.records[] | select(.type == "Job" and .parentId == $stageId)' | while read -r job; do
                local JOB_NAME=$(echo $job | jq -r '.name')
                local JOB_STATE=$(echo $job | jq -r '.state')
                local JOB_RESULT=$(echo $job | jq -r '.result // "pending"')
                local JOB_ID=$(echo $job | jq -r '.id')
                
                echo "  Job: $JOB_NAME - State: $JOB_STATE ($JOB_RESULT)"
                
                # Check for pending approvals
                if [[ "$JOB_STATE" == "pending" || "$STAGE_STATE" == "pending" ]]; then
                  # Get approval status
                  local APPROVALS=$(curl -s -X GET \
                    "https://dev.azure.com/{organization}/{project}/_apis/pipelines/approvals?api-version=7.0" \
                    -H "Authorization: Bearer ${{ secrets.AZURE_TOKEN }}" \
                    -H "Content-Type: application/json")
                  
                  local PENDING_APPROVAL=$(echo "$APPROVALS" | jq -r --arg buildId "$RUN_ID" \
                    '.value[] | select(.status == "pending" and .build.id == ($buildId | tonumber))')
                  
                  if [[ ! -z "$PENDING_APPROVAL" ]]; then
                    local APPROVAL_TYPE=$(echo "$PENDING_APPROVAL" | jq -r '.type')
                    local APPROVAL_INSTRUCTIONS=$(echo "$PENDING_APPROVAL" | jq -r '.instructions')
                    
                    echo "⚠️ WARNING: Pipeline requires approval"
                    echo "Type: $APPROVAL_TYPE"
                    echo "Instructions: $APPROVAL_INSTRUCTIONS"
                    echo "Stage: $STAGE_NAME"
                    echo "Job: $JOB_NAME"
                    echo "Please review and approve at: https://dev.azure.com/{organization}/{project}/_build/results?buildId=$RUN_ID"
                    exit 78  # Exit with warning status
                  fi
                fi
                
                # Get task details for failed jobs
                if [[ "$JOB_RESULT" == "failed" ]]; then
                  echo "    Failed Tasks:"
                  echo "$TIMELINE" | jq -c --arg jobId "$JOB_ID" \
                    '.records[] | select(.type == "Task" and .parentId == $jobId and .result == "failed")' | \
                    while read -r task; do
                    local TASK_NAME=$(echo $task | jq -r '.name')
                    local TASK_ERROR=$(echo $task | jq -r '.issues[].message // "No error message available"')
                    local TASK_LOG_URL=$(echo $task | jq -r '.log.url // "No log URL available"')
                    echo "      - Task: $TASK_NAME"
                    echo "        Error: $TASK_ERROR"
                    echo "        Logs: $TASK_LOG_URL"
                  done
                fi
              done
            done
            
            echo $STATUS
          }
          
          for ((i=1; i<=MAX_POLLS; i++)); do
            echo "Check $i/$MAX_POLLS"
            
            STATUS=$(monitor_pipeline)
            
            if [[ "$STATUS" == "completed" ]]; then
              # Get final result
              FINAL_RESULT=$(curl -s -X GET \
                "https://dev.azure.com/{organization}/{project}/_apis/build/builds/$RUN_ID?api-version=7.0" \
                -H "Authorization: Bearer ${{ secrets.AZURE_TOKEN }}" \
                -H "Content-Type: application/json" | jq -r '.result')
              
              if [[ "$FINAL_RESULT" == "succeeded" ]]; then
                echo "✅ Pipeline completed successfully"
                exit 0
              else
                echo "❌ Pipeline failed"
                exit 1
              fi
            fi
            
            echo "Waiting $POLL_INTERVAL_SECONDS seconds before next check..."
            sleep $POLL_INTERVAL_SECONDS
          done
          
          echo "⚠️ Timeout reached. Pipeline is still running."
          exit 1