name: Repository Issue Handler
on:
  issues:
    types: [opened, edited, reopened]

jobs:
  handle-repository-issue:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'repo-creation') || contains(github.event.issue.labels.*.name, 'repo-update')
    environment: cloud-platform
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_KEY }}
          owner: ${{ github.repository_owner }}
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml PyGithub
          
      - name: Process Repository Issue
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          ORG_NAME: ${{ github.repository_owner }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          python .github/scripts/process_repo_issue.py