name: Repository Sync
on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  sync-repositories:
    runs-on: ubuntu-latest
    environment: cloud-platform
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_KEY }}
          owner: ${{ github.repository_owner }}
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml PyGithub
          
      - name: Sync Repositories
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          ORG_NAME: ${{ github.repository_owner }}
        run: |
          python .github/scripts/repositories_sync.py