name: Team Configuration Setup

on:
    issues:
        types:
            - opened
            - reopened
            - edited

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
    process-team-configuration:
        runs-on: ubuntu-latest
        environment: 
          name: cloud-platform
        if: contains(github.event.issue.labels.*.name, 'team_user_maintain')
    
        steps:
          - uses: actions/create-github-app-token@v1
            id: app-token
            with:
              app-id: ${{ vars.APP_ID }}
              private-key: ${{ secrets.APP_KEY }}
              owner: ${{ github.repository_owner }}
    
          - name: Checkout repo
            uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.11'
    
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install PyYAML PyGithub gitpython


          - name: Process Team Configuration
            env:
              GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
              GITHUB_ORGANIZATION:  ${{ github.repository_owner }}
            run: python team_manage_user_membership.py