name: Team Configuration Setup

on:
    issues:
        types:
            - opened
            - reopened
            - edited

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
    process-team-configuration:
        runs-on: ubuntu-latest
        environment: 
          name: cloud-platform
        if: contains(github.event.issue.labels.*.name, 'team_setup') || contains(github.event.issue.labels.*.name, 'team_update')
    
        steps:
          - uses: actions/create-github-app-token@v1
            id: app-token
            with:
              app-id: ${{ vars.APP_ID }}
              private-key: ${{ secrets.APP_KEY }}
              owner: ${{ github.repository_owner }}
    
          - name: Checkout repo
            uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.11'
    
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install PyYAML PyGithub gitpython


          - name: Process Team Configuration
            env:
                GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
                ISSUE_PAYLOAD: ${{ toJson(github.event.issue) }}
            run: python scripts/process_team_configuration.py

          - name: Commit and Push Changes
            env: 
              ISSUE_ACTOR: ${{ github.event.issue.user.login }}
            run: |
              git config user.name "$ISSUE_ACTOR"
              git config user.email "$ISSUE_ACTOR@users.noreply.github.com"
              git add teams.yml
              git commit -m "Update teams configuration based on issue #${{ github.event.issue.number }}"
              git push

          - name: Parent teams remove
            env:
              GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
              GITHUB_ORGANIZATION: ${{ github.repository_owner }}
              GITHUB_REPOSITORY: ${{ github.repository }}
            run: |
              python scripts/team_manage_parent_teams.py
      
          - name: Parent teams setup
            id: setup-team
            env:
              GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
              GITHUB_ORGANIZATION: ${{ github.repository_owner }}
              GITHUB_REPOSITORY: ${{ github.repository }}
            run: |
              python scripts/team_setup_teams.py
    
          - name: Sync teams members
            if: steps.setup-team.outputs.exit_code == 0
            env:
              GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
              GITHUB_ORGANIZATION: ${{ github.repository_owner }}
              GITHUB_REPOSITORY: ${{ github.repository }}
              GITHUB_EVENT_BEFORE: ${{ github.event.before }}
              GITHUB_SHA: ${{ github.sha }}
              GITHUB_API_EVENT: "api-push"
            run: |
              python scripts/team_manage_membership.py
    
          - name: Sync teams resource
            if: steps.setup-team.outputs.exit_code == 0
            env:
              GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
              GITHUB_ORGANIZATION: ${{ github.repository_owner }}
              GITHUB_REPOSITORY: ${{ github.repository }}
              GITHUB_EVENT_BEFORE: ${{ github.workflow_sha }}
              GITHUB_SHA: ${{ github.sha }}
              GITHUB_API_EVENT: "api-push"
            run: |
              python scripts/team_manage_resource.py

          - name: Update Issue with Status
            if: success()
            uses: actions/github-script@v7
            with:
              script: |
                const issueNumber = context.issue.number;
                const teamConfig = require('./teams.yml');
                
                const comment = `### ✅ Team Setup Complete

                The default team configuration has been successfully created and committed to the repository.

                #### Current Configuration
                \`\`\`yaml
                ${require('fs').readFileSync('teams.yml', 'utf8')}
                \`\`\`

                #### How to Update Team Settings
                1. You can update the team configuration by creating a new issue using the "Update Team Configuration" template
                2. Or directly modify the \`teams.yml\` file and create a pull request

                #### Available Update Options:
                - Modify team members
                - Change repository permissions
                - Update team description
                - Adjust repository access
                - Configure parent/child team relationships

                To update, please:
                1. Create a new issue with label \`team_update\`
                2. Include the team name and the settings you want to modify
                3. The changes will be automatically processed and synced`;

                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issueNumber,
                  body: comment
                });
