name: PR Testing

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  test-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python - m pip install --upgrade pip
        pip install pytest PyYAML PyGithub gitpython

    - name: Run Unit Tests
      run: pytest .github/tests/*.py
