name: PR Testing

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  test-code:
    runs-on: ubuntu-latest
    environment: 
      name: cloud-platform
    
    steps:
    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ vars.APP_ID }}
        private-key: ${{ secrets.APP_KEY }}
        owner: ${{ github.repository_owner }}

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python - m pip install --upgrade pip
        pip install pytest pytest-cov pytest-mock PyYAML PyGithub gitpython

    - name: Run Unit Tests
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        GITHUB_ORGANIZATION: ${{ github.repository_owner }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        PYTHONPATH: ${{ github.workspace }}
        TESTING: "True"
      run: |
        pytest .github/tests/test_manage_parent_teams.py -v --cov=scripts --cov-report=term-missing
